// File Example1.idl
[
   // A unique identifier that distinguishes this interface from other interfaces.
   uuid(00000001-EAF3-4A7A-A0F2-BCE4C30DA77E),

   // This is version 1.0 of this interface.
   version(1.0)
]
interface Example1 // The interface is named Example1
{
   // Auth

	typedef struct
	{
		char login[64];
		char password[64];
	} user_dto;

	int sign_up(user_dto user);

	int sign_in(user_dto user);
	
	int get_users([out, size_is(count)] user_dto* buffer, int offset, int count);

   // Messages
}
